### ISSUE TITLE
No fallback for browsers without Javascript

### ISSUE THREAD

**Issue by progval** [masukomi/kudos#16]
When using a browser with Javascript disabled, there is no animation at all, nor is there any way to actually click the button. (The same holds true for svbtle.com)

You should at least provide a fallback like a classic &lt;a&gt; link, and eventually a :hover image.

**Comment by masukomi** [comment]
This is beyond the scope for this library. Making the 'a' link go somewhere is trivial but WHERE it goes and what it does when it gets there is a server side change and this is inherently coupled to the environment in which someone chooses to implement this library (rails, django, wordpress, etc) and that's WAY WAY beyond the scope of this. This is just a demo to showcase how to make this type of thing work.
