### ISSUE TITLE
Using with Jekyll/Octopress

### ISSUE THREAD

**Issue by gberger** [masukomi/kudos#19]
Does anyone have any clever idea on how to use this on a static blog (e.g, one generated by Jekyll or Octopress)?

**Comment by gberger** [comment]
One idea I had was using [Mongolab](https://mongolab.com/welcome/). Not sure about the implementation details.

**Comment by masukomi** [comment]
The concepts are somewhat at odds. Kudos require back-end code to associate a counts with articles, save that info, and then retrieve it. The demo method of storing a cookie per post is not scaleable. A static blog is all about NOT having back-end code. As soon as you introduce a database and code to count you've started into the land of dynamically generated pages, and if you're going to have dynamically generated pages then why use Jekyll?

Now, I see the argument that many static blogs use Disqus for their comments. And the Kudos could be made into a service like that, which I'm sure some people would use, but it'd cost a lot of money to host and handle hits from a pile of static blogs and I'm dubious that you'd be able to convince people to pay enough for it to cover the costs.

As for mongolab... they're just a database host. You would still need the connector code, and as far as i can tell MongoDB doesn't offer a direct HTTP endpoint that JavaScript could talk to. It'd be a big security risk if they did anyway. 

I'm thinking the real answer here is to consider switching to, or writing, a non-static blogging platform if you want to have dynamic information (a changing counter or anything else).

**Comment by masukomi** [comment]
I should note that while you were pondering doing with MongoDB probably isn't possible but I think it may be possible with CouchDB because i believe you can talk to CouchDB directly from client side JavaScript, and there's [free CouchDB hosting available here](http://www.iriscouch.com/).
