### ISSUE TITLE
Kudoable status

### ISSUE THREAD

**Issue by fabianofrancesconi** [masukomi/kudos#2]
I'm not very skilled with web stuff but it seems that your code doesn't catch the fact that a user already gave kudos for a specific ID.

I tested the html page but just after a refresh the page is back to normal.

**Comment by masukomi** [comment]
it does it via cookies. On line 47 of kudos.js it is set, on line 67 it checks for it when setting up the initial classes.  You can see a variant of this code in the MObtvse.com codebase and live on weblog.masukomi.org I forget what the issue is with it working on localhost.

**Comment by fabianofrancesconi** [comment]
It does work on your website, it does not on mine. I'm baffled :p

**Comment by masukomi** [comment]
hmm. unfortunately I'm booked for the rest of the weekend. But, if you haven't figured out anything by Monday I'll try and look at it. I know others have gotten it working. In the meantime, [here's the code MObtvse is using](https://github.com/masukomi/mobtvse/blob/master/app/assets/javascripts/kudos.js.erb)... maybe something will become evident if you compare them.

**Comment by fabianofrancesconi** [comment]
Thank you very much. It seems that it creates a cookie named "undefined". Probably there's something wrong in my settings. By the way, the website is: http://blog.encomiabile.it

**Comment by masukomi** [comment]
Glad you got it working. I'll make the code give the cookie a name, and make it obvious and easy to change.

**Comment by fabianofrancesconi** [comment]
Thank you very much. I had some troubles because I'm far to be a web designer, developer or something similar.

Thank you for your work!
