### ISSUE TITLE
any plan for wordpress plugin

### ISSUE THREAD

**Issue by ijafri** [masukomi/kudos#4]
I'd appreciate if you could turn it into a wordpress plugin

**Comment by masukomi** [comment]
I hadn't considered that actually, but thanks for the suggestion. It's a good idea.

**Comment by ahoereth** [comment]
Just saw the post now. I actually published a WordPress plugin using this: http://wordpress.org/extend/plugins/kudos/ & https://github.com/ahoereth/wordpress-kudos

**Comment by masukomi** [comment]
Major thanks for that putting that together and your pull-request @ahoereth :)
