### ISSUE TITLE
jQuery version

### ISSUE THREAD

**Issue by lkorth** [masukomi/kudos#7]
I'm using this widget on my site with jQuery 1.8.3, but it appears to break with 1.9.

**Comment by masukomi** [comment]
I'll try and look into it soon. In the meantime any error messages you can provide, or even a description of how it is breaking, will help to make the debugging faster.

**Comment by lkorth** [comment]
Using jQuery 1.9.0 the first error (Object [object Object] has not method 'live') happens on page load and the second error happens when you mouse over the kudo and the fill gets big enough to hit the outer circle, this error happens and it fails to kudo. 

![Capture](https://f.cloud.github.com/assets/1163999/111421/17c2d944-6af5-11e2-8b18-ac3b63c3bbbc.PNG)

Thanks for the awesome widget!

**Comment by pehrlich** [comment]
Resolved here: https://github.com/masukomi/kudos/pull/9
